import type { SchoolHolidays } from './settings.ts';

export * from './user.ts';
export * from './category.ts';
export * from './course.ts';
export * from './customer.ts';
export * from './target.ts';
export * from './instructor.ts';
export * from './location.ts';
export * from './module.ts';
export * from './news.ts';
export * from './post.ts';
export * from './registration.ts';
export * from './room.ts';
export * from './text.ts';
export * from './settings.ts';
export * from './event.ts';
export * from './participant.ts';
export * from './attendance.ts';
export * from './chat.ts';
